### ISSUE TITLE
Error: Cannot find module '/github/workspace/index.js'

### ISSUE THREAD

**Issue by vedmant** [mmarchini-oss/npm-otp-publish#69]
I have following setup:

```
name: Publish Package

on:
  release:
    types: [published]

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mmarchini-oss/npm-otp-publish@v0
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_actor: ${{ github.actor }}
          version_url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}
```

It shows error:
```
Run mmarchini-oss/npm-otp-publish@v0
  with:
    npm_token: ***
    github_token: ***
    github_actor: vedmant
    version_url: https://github.com/vedmant/nuxt3-vuex/releases/tag/
    notifier: github-issue
    timeout: 15
    github_release_team: github-issue
/usr/bin/docker run --name c3d7c1[2](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:2)c7cc824fa08c78[3](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:3)16dea5a[4](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:4)4ec_b13904 --label 498[5](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:5)9c --workdir /github/workspace --rm -e "INPUT_NPM_TOKEN" -e "INPUT_GITHUB_TOKEN" -e "INPUT_GITHUB_ACTOR" -e "INPUT_VERSION_URL" -e "INPUT_NPM_USER" -e "INPUT_NOTIFIER" -e "INPUT_TIMEOUT" -e "INPUT_GITHUB_RELEASE_TEAM" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/nuxt3-vuex/nuxt3-vuex":"/github/workspace" 49859c:3d7c12c7cc824fa08c7831[6](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:6)dea5a44ec  "--npm-user=" "--version-url=https://github.com/vedmant/nuxt3-vuex/releases/tag/" "--npm-token=***" "--github-token=***" "--notifier=github-issue" "--github-actor=" "--github-release-team="
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/github/workspace/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:[7](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:7)46:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:[12](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:13))
    at internal/main/run_main_module.js:[17](https://github.com/vedmant/nuxt3-vuex/actions/runs/4213792037/jobs/7313774596#step:4:18):47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
